apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

nameSuffix: -dev

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: nginx-deploy
